server:
  port: 8082

spring:
  application:
    name: user-profile-service

  # Database Connection
  datasource:
    url: jdbc:postgresql://localhost:5433/skillmatching
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:db123}
    driver-class-name: org.postgresql.Driver

  # Hibernate Settings (Auto-creates our tables)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

minio:
  url: http://localhost:9000
  access-key: ${MINIO_ROOT_USER:minioadmin}
  secret-key: ${MINIO_ROOT_USER:minioadmin}
  bucket-name: resumes

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true