server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Removed the conflicting globalcors block here!
      server:
        webmvc:
          routes:
            - id: auth-service-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
                
            - id: profile-service-route
              uri: lb://USER-PROFILE-SERVICE
              predicates:
                - Path=/profile/**
                
            - id: jobs-service-route
              uri: lb://USER-PROFILE-SERVICE
              predicates:
                - Path=/jobs/**
                
            - id: career-graph-service-route
              uri: lb://CAREER-GRAPH-SERVICE
              predicates:
                - Path=/graph/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true