spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # Since this IS the server, it doesn't need to register itself or fetch a registry.
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0